export const heroSlides = [
  {
    id:'indoor',direction:'right',palette:'31, 20, 14',glow:'214, 83, 25',gold:'244, 183, 74',
    label:['Indoor dining','ইনডোর ডাইনিং'],kicker:['FULLY AIR-CONDITIONED DINING','সম্পূর্ণ শীতাতপনিয়ন্ত্রিত ডাইনিং'],
    title:['Come for the food.','খাবারের টানে আসুন,'],accent:['Stay for the moments.','সময়টা হোক আপন।'],
    description:['A calm, fully air-conditioned dining room where warm light, comfortable seating and thoughtful details make every meal feel more inviting.','শান্ত ও সম্পূর্ণ শীতাতপনিয়ন্ত্রিত ডাইনিং। উষ্ণ আলো, আরামদায়ক বসার ব্যবস্থা আর যত্নে সাজানো পরিবেশে পরিবার ও বন্ধুদের সঙ্গে কাটুক সুন্দর সময়।'],
    detail:['Air-conditioned comfort · Warmly designed interiors','শীতাতপনিয়ন্ত্রিত পরিবেশ · যত্নে সাজানো ইনডোর'],
    caption:['The main air-conditioned dining room','আমাদের প্রধান শীতাতপনিয়ন্ত্রিত ডাইনিং'],
    alt:['Cafe Aronno air-conditioned dining room with warm pendant lights, booth seating and the Good Food wall','উষ্ণ পেনডেন্ট লাইট, বুথ সিটিং ও গুড ফুড দেয়ালসহ ক্যাফে অরণ্যের শীতাতপনিয়ন্ত্রিত ডাইনিং'],
    position:'50% 53%',mobilePosition:'50% 50%',width:1086,height:1448,action:['Explore the menu','মেনু দেখুন'],href:'/menu',
  },
  {
    id:'lounge',direction:'right',palette:'12, 24, 28',glow:'0, 145, 214',gold:'239, 177, 66',
    label:['Signature interior','বিশেষ ইনডোর'],kicker:['DESIGN IS PART OF THE EXPERIENCE','সাজসজ্জাই আমাদের বিশেষত্ব'],
    title:['Made to feel','আপনার মনের মতো,'],accent:['beautifully yours.','সাজানো এক অরণ্য।'],
    description:['Fresh greenery, warm light and thoughtful details shape every corner with care. From an unhurried meal to a special celebration, our team is ready to create a setting that feels personal to you.','সবুজের সতেজতা, উষ্ণ আলো আর রুচিশীল ইন্টেরিয়রে প্রতিটি কোণ সাজানো হয়েছে যত্নে। নিরিবিলি খাবার, প্রাণখোলা আড্ডা কিংবা বিশেষ দিনের আয়োজন—আপনার পছন্দের আবহ তৈরি করতে আমাদের টিম প্রস্তুত।'],
    detail:['Thoughtful décor · Styled for your occasion','যত্নে সাজানো পরিবেশ · আপনার পছন্দের আয়োজন'],
    caption:['Greenery and colour in our signature indoor space','সবুজ ও রঙে সাজানো আমাদের বিশেষ ইনডোর'],
    alt:['Cafe Aronno indoor lounge with hanging greenery, orange feature wall, blue alcoves and warm lights','ঝুলন্ত সবুজ গাছ, কমলা দেয়াল, নীল খিলান ও উষ্ণ আলোয় ক্যাফে অরণ্যের ইনডোর'],
    position:'50% 54%',mobilePosition:'54% 52%',width:1086,height:1448,action:['Discover our spaces','পরিবেশ দেখুন'],href:'/spaces',
  },
  {
    id:'entrance',direction:'right',palette:'26, 22, 18',glow:'190, 58, 51',gold:'227, 178, 74',
    label:['Cafe entrance','ক্যাফের প্রবেশপথ'],kicker:['YOUR TIME AT ARONNO STARTS HERE','অরণ্যে আপনার সময় শুরু হোক এখানেই'],
    title:['Step through the door,','প্রবেশ করুন অরণ্যে,'],accent:['leave the rush behind.','ব্যস্ততা থাকুক বাইরে।'],
    description:['Beyond this welcoming entrance, thoughtfully styled indoor and outdoor spaces are ready for relaxed meals, warm conversations and your special occasions.','এই আন্তরিক প্রবেশপথের ওপারে অপেক্ষায় যত্নে সাজানো ইনডোর ও আউটডোর পরিসর। পরিবার, বন্ধু কিংবা প্রিয়জনদের সঙ্গে নিরিবিলি খাবার, প্রাণখোলা আড্ডা ও বিশেষ আয়োজনের জন্য ক্যাফে অরণ্যে আপনাকে স্বাগতম।'],
    detail:['A welcoming entrance · Indoor and outdoor seating','স্বাগত প্রবেশপথ · ইনডোর ও আউটডোর বসার আয়োজন'],
    caption:['The welcoming entrance to Cafe Aronno','ক্যাফে অরণ্যের স্বাগত প্রবেশপথ'],
    alt:['Daytime entrance of Cafe Aronno with its Bengali sign, hanging greenery and open gates','বাংলা সাইনবোর্ড, ঝুলন্ত সবুজ লতা ও খোলা ফটকসহ দিনের আলোয় ক্যাফে অরণ্যের প্রবেশপথ'],
    position:'50% 43%',mobilePosition:'56% 45%',width:1536,height:2048,action:['Plan your visit','ভিজিটের তথ্য দেখুন'],href:'/visit',
  },
  {
    id:'outdoor-garden',direction:'right',palette:'10, 28, 22',glow:'37, 139, 92',gold:'244, 190, 77',
    label:['Garden seating','বাগানের বসার জায়গা'],kicker:['GARDEN DINING IN THE OPEN AIR','সবুজ বাগানে খোলামেলা আয়োজন'],
    title:['Dine among the green,','সবুজের মাঝে বসুন,'],accent:['stay a little longer.','সময়টা হোক আরও আপন।'],
    description:['Garden umbrellas, open-air tables and lush greenery beside the pond make room for relaxed meals, family time and long conversations with friends beneath the open sky.','গাছের ছায়া, রঙিন ছাতা আর পুকুরপাড়ের সবুজে ঘেরা সুবিশাল আউটডোর। দিনের খোলা আলোয় খাবার, পরিবার নিয়ে নিরিবিলি সময় কিংবা বন্ধুদের দীর্ঘ আড্ডা—প্রতিটি মুহূর্ত এখানে আরও সতেজ ও স্বচ্ছন্দ।'],
    detail:['Garden umbrellas · Pondside open-air seating','বাগানের ছাতা · পুকুরপাড়ে খোলামেলা বসার আয়োজন'],
    caption:['Spacious garden seating beside the pond','পুকুরপাড়ে আমাদের সুবিশাল সবুজ আউটডোর'],
    alt:['Cafe Aronno garden seating with red and white umbrellas, green trees and a pond in the foreground','লাল-সাদা ছাতা, সবুজ গাছপালা ও সামনের পুকুরসহ ক্যাফে অরণ্যের বাগানের বসার জায়গা'],
    position:'50% 43%',mobilePosition:'46% 50%',width:1086,height:1448,action:['Explore the garden','বাগান ও পরিবেশ দেখুন'],href:'/spaces',
  },
] as const;
